### ISSUE TITLE
assertion failure: last>=first

### ISSUE THREAD

**Issue by lkmack21** [OceanGenomics/mudskipper#35]
I am attempting to do a bulk RNA-Seq genome alignment conversion to transcriptome coordinates and keep encountering this error: 

thread 'main' panicked at 'assertion failed: last >= first', /home/lkmack/.cargo/registry/src/github.com-1ecc6299db9ec823/coitrees-0.2.1/src/lib.rs:196:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I'm having a hard time figuring out if this is indicating an issue in my bam files or in my gtf file. 

So far, I have checked the gtf file to ensure the start and stop coordinates are correct which they are. I have also run a second samtools sort attempt on my bam files in case this was the issue with no luck. Any pointers are appreciated.

**Comment by lkmack21** [comment]
backtrace: 

thread 'main' panicked at 'assertion failed: last >= first', /home/lkmack/.cargo/registry/src/github.com-1ecc6299db9ec823/coitrees-0.2.1/src/lib.rs:196:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: mudskipper::convert::find_tid
   4: mudskipper::convert::convert_single_end
   5: mudskipper::convert::convert_query_bam_records
   6: mudskipper::bam::bam2bam
   7: mudskipper::main

**Comment by physnano** [comment]
I am having the same error.
