### ISSUE TITLE
Error in reading annotation file.

### ISSUE THREAD

**Issue by anoronh4** [OceanGenomics/mudskipper#42]
hello! I hope this message finds you well. I'm excited to use this tool. I am getting the following output from mudskipper:
```
mudskipper index -g genome.gtf -d mdsk_idx 
[2023-11-10T21:36:10Z INFO  mudskipper] Mudskipper started...
[2023-11-10T21:36:10Z INFO  mudskipper::annotation] reading the gtf file and building the tree.
thread 'main' panicked at 'Error in reading annotation file.: Failed to read GFF from "genome.gtf"

Caused by:
    No such file or directory (os error 2)', src/annotation.rs:34:62
stack backtrace:
   0:     0x561cf43f92bc - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x561cf43f92bc - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561cf43f92bc - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x561cf43f92bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x561cf441a4ec - core::fmt::write::h513b07ca38f4fb1b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:     0x561cf43f5e75 - std::io::Write::write_fmt::haf8c932b52111354
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:     0x561cf43fac50 - std::sys_common::backtrace::_print::h195c38364780a303
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x561cf43fac50 - std::sys_common::backtrace::print::hc09dfdea923b6730
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x561cf43fac50 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:     0x561cf43fa805 - std::panicking::default_hook::h60284635b0ad54a8
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:     0x561cf43fb304 - std::panicking::rust_panic_with_hook::ha677a669fb275654
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
  11:     0x561cf43fade0 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
  12:     0x561cf43f9764 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x561cf43fad49 - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  14:     0x561cf422d6c1 - core::panicking::panic_fmt::h35f3a62252ba0fd2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  15:     0x561cf422d7b3 - core::result::unwrap_failed::hb53671404b9e33c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
  16:     0x561cf425dcf9 - mudskipper::annotation::build_tree::ha6690eb761e85bf6
  17:     0x561cf423c21f - mudskipper::main::he54c8a7786ae8869
  18:     0x561cf42358a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2f9d51d9957b9fc3
  19:     0x561cf4252bc9 - std::rt::lang_start::{{closure}}::hfb6f3d7d04aa35da
  20:     0x561cf43f8f4b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7e688d7cdfeb7e00
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
  21:     0x561cf43f8f4b - std::panicking::try::do_call::h4be824d2350b44c9
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  22:     0x561cf43f8f4b - std::panicking::try::h0a6fc7affbe5088d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  23:     0x561cf43f8f4b - std::panic::catch_unwind::h22c320f732ec805e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  24:     0x561cf43f8f4b - std::rt::lang_start_internal::{{closure}}::hd38309c108fe679d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
  25:     0x561cf43f8f4b - std::panicking::try::do_call::h8fcaf501f097a28e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  26:     0x561cf43f8f4b - std::panicking::try::h20e906825f98acc1
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  27:     0x561cf43f8f4b - std::panic::catch_unwind::h8c5234dc632124ef
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  28:     0x561cf43f8f4b - std::rt::lang_start_internal::hc4dd8cd3ec4518c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
  29:     0x561cf423e2a2 - main
  30:     0x7f10d908009b - __libc_start_main
  31:     0x561cf422de61 - <unknown>
```
i tried to convert to other formats using agat and gffread, but still get the same message. in fact no matter the extension it says `Failed to read GFF`, so i wonder if it is correctly registering the file extension/type, but even when i have a gff it still fails. i am not  very familiar with rust and was hoping you might help me interpret the backtrace or have ideas on the issue with my gtf. 

btw i am using the following container: `docker://quay.io/biocontainers/mudskipper:0.1.0--h9f5acd7_1`.

**Comment by anoronh4** [comment]
here's a few lines from the beginning of my gtf file (this is from a test reference set, which is why it starts with chr22):
```
chr22	havana	gene	1	2611	.	+	.	gene_id "ENSG00000233995"; gene_version "1"; gene_name "AP000547.1"; gene_source "havana"; gene_biotype "unprocessed_pseudogene";
chr22	havana	transcript	1	2611	.	+	.	gene_id "ENSG00000233995"; gene_version "1"; transcript_id "ENST00000454360"; transcript_version "1"; gene_name "AP000547.1"; gene_source "havana"; gene_biotype "unprocessed_pseudogene"; transcript_name "AP000547.1-201"; transcript_source "havana"; transcript_biotype "unprocessed_pseudogene"; tag "basic"; transcript_support_level "NA";
chr22	havana	exon	1	124	.	+	.	gene_id "ENSG00000233995"; gene_version "1"; transcript_id "ENST00000454360"; transcript_version "1"; exon_number "1"; gene_name "AP000547.1"; gene_source "havana"; gene_biotype "unprocessed_pseudogene"; transcript_name "AP000547.1-201"; transcript_source "havana"; transcript_biotype "unprocessed_pseudogene"; exon_id "ENSE00001732752"; exon_version "1"; tag "basic"; transcript_support_level "NA";
chr22	havana	exon	682	727	.	+	.	gene_id "ENSG00000233995"; gene_version "1"; transcript_id "ENST00000454360"; transcript_version "1"; exon_number "2"; gene_name "AP000547.1"; gene_source "havana"; gene_biotype "unprocessed_pseudogene"; transcript_name "AP000547.1-201"; transcript_source "havana"; transcript_biotype "unprocessed_pseudogene"; exon_id "ENSE00001623204"; exon_version "1"; tag "basic"; transcript_support_level "NA";
```
i discovered that mudskipper was working fine with my full-sized gtfs, so i thought it might have something to do with the content of this gtf file, but i can't see the issue so far.

**Comment by anoronh4** [comment]
i've discovered an error in my commands that is unrelated to mudskipper. i'll go ahead and close the issue.
